version: '3'

services:
  postgres_backend:
    build:
      context: ./sql
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: sqlMaxSql
    ports:
      - "5434:5432"
    container_name: lamp_postgres_instance


  lamp_control_api:
    build:
      context: ./lamp_control_api
      dockerfile: Dockerfile
    volumes:
      - ./lamp_control_api:/app
    ports:
      - "9999:9999"
    container_name: lamp_control_api_instance
    depends_on:
      - postgres_backend
