name: jeka_lamp_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.2.2 
  # cache
  shared_preferences: ^2.3.3
  internet_connection_checker: ^3.0.1
  # bloc and cubit
  flutter_bloc: ^8.1.6
  # DI
  get_it: ^8.0.3
  # image
  cached_network_image: ^3.4.1
  flutter_blue_plus: ^1.34.5

flutter:
  uses-material-design: true
